name: big-bear-dbgate
services:
  big-bear-dbgate:
    container_name: big-bear-dbgate
    image: dbgate/dbgate:7.1.11-alpine
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-dbgate/config
        target: /root/.dbgate
    labels:
      icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/dbgate/logo.png
